### ISSUE TITLE
Add Prettier to project

### ISSUE THREAD

**Issue by jarvisenlaura** [Twig-the-code/nakittaja#4]
Prettier pitää huolen koodin muotoilusta, jotta kaikkien tekemä koodi näyttää samalta

**Comment by LadyEpona** [comment]
If using VSCode remember to install Prettier extension locally. Once installed open File > Preferences > Settings, search 'format'. Make sure
1. Editor: Default Formatter = Prettier
and
2. Editor: Format on Save is ticked.
