### ISSUE TITLE
Add ESLint to project

### ISSUE THREAD

**Issue by jarvisenlaura** [Twig-the-code/nakittaja#5]
eslint, eslint-config-prettier, eslint-plugin-prettier, eslint-plugin-react, eslint-plugin-react-native (eslint-plugin-jest, eslint-plugin-testing-library, eslint-plugin-react-hooks)

**Comment by jarvisenlaura** [comment]
And make it work with prettier

**Comment by LadyEpona** [comment]
Remember to put these in devDependencies (include **--save-dev** flag in the npm install). If using VSCode remember to install ESlint extension locally.
